export default {
  background: `.c-forms-form`,
  wrapper: `.cognito:not(.c-forms-actionBar)`,
  title: `.c-forms-heading h2`,
  titleSection: `.c-forms-form-title`,
  pageNumber: `.c-page-numbering`,
  label: `.cognito .c-label label, .cognito .c-label`,
  buttons: {
    submit: `#c-submit-button`,
    previous: `.c-page-previous-page`,
    next: `.c-page-next-page`,
    upload: `.c-upload-button button`,
    addItem: `.c-add-item`,
  },
  pages: {
    section: `.c-progress-section`,
    page: `.c-progress-steps li`,
    selectedPage: `.c-progress-steps li.c-page-selected`,
  },
  section: `.c-section`,
  action: `.c-action`,
  helpText: `.c-helptext`,
  error: `.cognito .c-forms-form .c-validation`,
  placeholder: `.cognito ::placeholder, .cognito .c-forms-form input::placeholder`,
  confirmation: `.c-forms-confirmation-message`,
  confirmationPage: `.c-forms-confirmation`,
  input: {
    text: `.cognito input[type=text]`,
    textarea: `.cognito textarea`,
    dropdown: `.c-dropdown`,
  },
  field: `.c-field`,
  fields: {
    text: {
      single: `.c-text-singleline`,
      multi: `.c-text-multiplelines`,
    },
    choice: {
      dropdown: `.c-choice-dropdown`,
      radio: `.c-choice-radiobuttons`,
      checkboxes: `.c-choice-checkboxes`,
    },
    yesNo: {
      checkbox: `.c-yesno-checkbox`,
      radio: `.c-yesno-radiobuttons`,
      toggle: `.c-yesno-toggle`,
      toggleContainer: `.c-toggle--container`,
    },
    dateTime: {
      date: `.c-date-date`,
      time: `.c-date-time`,
    },
    currency: `.c-currency`,
    number: {
      integer: `.c-number-integer`,
      decimal: `.c-number-decimal`,
      percent: `.c-number-percent`,
    },
    name: `.c-name`,
    address: `.c-address`,
    phone: `.c-phone`,
    email: `.c-email`,
    website: `.c-website`,
    signature: `.c-signature`,
    likert: `.c-rating-scale`,
    section: `.c-section`,
    file: `.c-file`,
    repeatingSection: `.c-repeating-section-group > div:not(.c-table-row)`,
    repeatingSectionItem: `.c-repeating-section-item`,
    editor: `.c-editor`,
    html: `.c-html`,
    upload: `.c-fileupload`,
  },
  icons: {
    remove: `.remove-icon`,
    signature: `.c-signature-glyph`,
  },
};
